### ISSUE TITLE
The breakpoint function cannot be implemented

### ISSUE THREAD

**Issue by chen-xiaoxing** [KamiC6238/monaco-breakpoints#2] opened 2024-05-11 03:08 UTC
Hello, can you please help me find out why the breakpoint function cannot be implemented? The following is the relevant version number I use：
 
    "monaco-breakpoints": "^0.1.2",
    "Monaco Editor": "^0.48.0",
    "monaco-editor-webpack-plugin": "^7.1.0",
    "terser-webpack-plugin": "^5.3.10",
    "vue": "^3.2.13",
    "vue-router": "^4.0.3"

**Comment by chen-xiaoxing** [comment] 2024-05-11 03:09
this is my code:
<template>
    <el-drawer v-model="drawerVisable" direction="rtl" size="100%">
            <span>输入</span>
            <div class="editor" ref="aceInputRef"></div>
    </el-drawer>
</template>

<script setup lang="ts">
import { ref, computed, defineEmits, defineProps, defineExpose, nextTick, watch, onMounted } from "vue";
// import * as monaco from 'monaco-editor/esm/vs/editor/editor.api.js';
import * as monaco from 'monaco-editor';
import { MonacoBreakpoint } from 'monaco-breakpoints';

const props = defineProps(['statusList']);
const emit = defineEmits(['sendSocket', 'clearSelect']);

const drawerVisable = ref(true);
const aceInputRef = ref(null);
const editorInput = ref(null);

onMounted(() => {
    nextTick(() => {
        editorInput.value = monaco.editor.create(aceInputRef.value, {
            value: `sub Main()
    Dim a As New M8Ball

    Do While True

        Dim q As String = ""
        Console.Write("ask me about the future... ")
        q = Console.ReadLine()

        If q.Trim <> "" Then
            Console.WriteLine("the answer is... {0}", a.getAnswer(q))
        Else
            Exit Do
        End If
    Loop

End sub`,
            language: "vb",
            automaticLayout: true,
            minimap: {
                enabled: false,
            },
            glyphMargin: true, // 启用图形边距渲染
            folding: true, // 折叠
            theme: "vs",
        })
        
        const instance = new MonacoBreakpoint({ editor: editorInput.value });

        console.log(instance, 'instance');

        instance.on('breakpointChanged', breakpoints => {
            console.log('breakpointChanged: ', breakpoints);
        })

        // highlight background for the passed line number
        // instance.setLineHighlight(1)

        // remove the current highlight background
        // instance.removeHighlight();

    })
})

</script>

<style>
.editor {
    width: 100%;
    height: 500px;
}

.monaco-editor.no-user-select .view-lines {
    text-align: left;
}

.monaco-hover-breakpoint {
    width: 10px !important;
    height: 10px !important;
    border-radius: 100%;
    background-color: #eabebc;
    margin: 4px 0 0 8px;
    cursor: pointer;
}

.monaco-breakpoint {
    width: 10px !important;
    height: 10px !important;
    border-radius: 100%;
    background-color: #d47d78;
    margin: 4px 0 0 8px;
    cursor: pointer;
}

.monaco-line-highlight {
    background-color: rgba(245, 240, 187, 0.5);
}
</style>

**Comment by KamiC6238** [comment] 2024-05-11 03:29
Hi @chen-xiaoxing, can you format your code? It doesn't look very clean that way. As well as please mark which line of code is not working, thanks.

**Comment by chen-xiaoxing** [comment] 2024-05-11 03:38
// The highlighting and folding functions are available, but the breakpoint function is not implemented.

import { ref, computed, defineEmits, defineProps, defineExpose, nextTick, watch, onMounted } from "vue";
import * as monaco from 'monaco-editor'; 
import { MonacoBreakpoint } from 'monaco-breakpoints';

const props = defineProps(['statusList']); 
const emit = defineEmits(['sendSocket', 'clearSelect']); 
const drawerVisable = ref(true); 
const aceInputRef = ref(null); 
const editorInput = ref(null); 

onMounted(() => { 
    nextTick(() => { 
        editorInput.value = monaco.editor.create(aceInputRef.value, { 
            value: `sub Main() Dim a As New M8Ball Do While True Dim q As String = "" Console.Write("ask me about the future... ") q = Console.ReadLine() If q.Trim <> "" Then Console.WriteLine("the answer is... {0}", a.getAnswer(q)) Else Exit Do End If Loop End sub`,
             language: "vb", 
             automaticLayout: true, 
             minimap: { enabled: false, }, 
             glyphMargin: true, 
             folding: true, 
             theme: "vs",
        }) 
        const instance = new MonacoBreakpoint({ editor: editorInput.value }); 
        instance.on('breakpointChanged', 
             breakpoints => { 
                 console.log('breakpointChanged: ', breakpoints);
              }
         ) 
    })
 })

**Comment by KamiC6238** [comment] 2024-05-11 03:53
Hi @chen-xiaoxing, Can you provide a minimal reproducible demo?
Or have you tried the following writeup?
```typescript
const editor = monaco.editor.create(...)
const instance = new MonacoBreakpoint({ editor });
editorInput.value = editor
```

**Comment by KamiC6238** [comment] 2024-05-11 03:55
I'm not sure if it's because `editorInput.value` hasn't been assigned yet when you initialized the `MonacoBreakpoint` instance.

**Comment by chen-xiaoxing** [comment] 2024-05-11 05:48
Yes, that's the reason, thank you, do you know why you can't set it directly to editorInput?

**Comment by KamiC6238** [comment] 2024-05-11 06:19
I think this is because the `nextTick callback function` is executed asynchronously, meaning the code that initializes the `MonacoBreakpoints` instance is executed before the code in the callback function. I think you can verify this with `console.log`.

Then it looks like your problem is solved for now, so I would close the issue. If you still have any questions, please feel free to re-open, thanks!

**Closed as completed by KamiC6238** 2024-05-11 06:19 UTC
